name: Build

on:
  push:
    paths-ignore:
      - 'build/**'
      - 'docs/**'
      - 'files/**'

jobs:

  Create_Build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install packages
        run: npm ci

      - name: === building three ===
        run: npm run build && npm run build-module && npm run build-examples

      - name: === Giving permission to build script ===
        run: chmod +x ./utils/three-production.sh

      - name: === Running build script ===
        run: sh ./utils/three-production.sh
        env:
          API_TOKEN_GITHUB: ${{ secrets.WEBA_BOT_PAT }}
          INPUT_DESTINATION_BASE_BRANCH: 'main'
          INPUT_DESTINATION_HEAD_BRANCH: 'threejs-bump'
          PULL_REQUEST_REVIEWERS: 'abeersaqib'   

      - name: Create Pull Request in weba/three.js
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            build/three.module.js
            examples/jsm/*
            package.json
