name: CI

on:
  pull_request:
    paths-ignore:
      - 'build/**'
      - 'docs/**'
      - 'files/**'
  push:
    paths-ignore:
      - 'build/**'
      - 'docs/**'
      - 'files/**'

permissions:
  contents: read

jobs:
  lint:
    name: "Lint testing"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install packages
        run: npm ci

      - name: === Lint testing ===
        run: npm run lint

  unit:
    name: "Unit testing"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build

      - name: === Unit testing ===
        run: npm run test-unit

  e2e:
    name: "E2E testing"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        CI: [ 0, 1, 2, 3, 4, 5, 6, 7 ]
    env:
      CI: ${{ matrix.CI }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build

      - name: === E2E testing ===
        run: npm run test-e2e

  e2e-cov:
    name: "Examples ready for release"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install packages
        run: npm ci

      - name: === Examples ready for release ===
        run: npm run test-e2e-cov
